language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get golang.org/x/sys/unix
  - go get golang.org/x/sys/windows
  - go get github.com/lib/pq
  - go get golang.org/x/crypto/bcrypt
services:
  - postgresql
script:
 - go install -v ./...