language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get golang.org/x/sys/unix
  - go get golang.org/x/sys/windows
script:
  - go test -race -v ./...