language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get golang.org/x/sys/unix
  - go get golang.org/x/sys/windows
services:
  - postgresql
before_script:
  - sleep 15
script:
 - go install -v ./...