language: go
go:
  - 1.9.x
  - tip
env:
  - GOMAXPROCS=4 GORACE=halt_on_error=1
install:
  - go get golang.org/x/sys/unix
  - go get golang.org/x/sys/windows
  - go get github.com/lib/pq
  - go get golang.org/x/crypto/bcrypt
  - go get github.com/sirupsen/logrus
  - go get github.com/jinzhu/gorm
services:
  - postgresql
script:
 - go install -v ./...